CREATE TABLE APPLICATIONUSER(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	USERNAME NVARCHAR(256) NOT NULL,
	NORMALIZEDUSERNAME NVARCHAR(256) NOT NULL,
	EMAIL NVARCHAR(256) NULL,
	NORMALIZEDEMAIL NVARCHAR(256)  NULL,
	EMAILCONFIRMED BIT NOT NULL,
	PASSWORDHASH NVARCHAR(MAX) NULL,
	PHONENUMBER NVARCHAR(50) NULL,
	PHONENUMBERCONFIRMED BIT NOT NULL,
	TWOFACTORENABLED BIT NOT NULL
);

CREATE INDEX IX_APPLICATIONUSER_NORMALIZEDUSERNAME ON APPLICATIONUSER (NORMALIZEDUSERNAME) ;

CREATE INDEX IX_APPLICATIONUSER_NORMALIZEDEMAIL ON APPLICATIONUSER (NORMALIZEDEMAIL) ;


CREATE TABLE APPLICATIONROLE(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	USERNAME NVARCHAR(256) NOT NULL,
	NORMALIZEDUSERNAME NVARCHAR(256) NOT NULL,
);

CREATE INDEX IX_APPLICATIONROLE_NORMALIZEDUSERNAME ON APPLICATIONROLE (NORMALIZEDUSERNAME) ;


CREATE TABLE APPLICATIONUSERROLE(
	USERID INT NOT NULL,
	ROLEID INT NOT NULL,
	PRIMARY KEY (USERID,ROLEID),
	CONSTRAINT FK_APPLICATIONUSER_USER FOREIGN KEY (USERID) REFERENCES APPLICATIONUSER(ID),
	CONSTRAINT FK_APPLICATIONROLE_ROLE FOREIGN KEY (ROLEID) REFERENCES APPLICATIONROLE(ID)
);


